spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
  api-docs:
    path: /api-docs
  info:
    title: Extension Manager API
    description: API for managing SuperAdmin registration and other extension manager functionalities
    version: 1.0.0
    contact:
      name: springcore
      email: springcore.africa@gmail.com
  packages-to-scan: com.oracleous.extention_manager
  paths-to-match: /api/**,/auth/**,/admin/**,/investor,/local_admin,/user/,/super_admin
